// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGzEwBZM_FjPXv-jl7FxSITNVYl7ZMPC8',
    appId: '1:44313752556:web:01d0b048fdfc390591c6c9',
    messagingSenderId: '44313752556',
    projectId: 'coby-facturacion',
    authDomain: 'coby-facturacion.firebaseapp.com',
    storageBucket: 'coby-facturacion.appspot.com',
    measurementId: 'G-SZ66MHCFL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChSI09gr_RQtEe6U9fifyf5uSeujPmSLw',
    appId: '1:44313752556:android:2397d4cbb8e6be5e91c6c9',
    messagingSenderId: '44313752556',
    projectId: 'coby-facturacion',
    storageBucket: 'coby-facturacion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmkO2mdNhMRynUE1KGfsxwo-1fZOB5VeU',
    appId: '1:44313752556:ios:779b4022599ae32d91c6c9',
    messagingSenderId: '44313752556',
    projectId: 'coby-facturacion',
    storageBucket: 'coby-facturacion.appspot.com',
    iosBundleId: 'com.example.inventarioapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmkO2mdNhMRynUE1KGfsxwo-1fZOB5VeU',
    appId: '1:44313752556:ios:779b4022599ae32d91c6c9',
    messagingSenderId: '44313752556',
    projectId: 'coby-facturacion',
    storageBucket: 'coby-facturacion.appspot.com',
    iosBundleId: 'com.example.inventarioapp',
  );
}
